# 1. Conecta al Service de PostgreSQL en K8s ("postgres-service")
spring.datasource.url=jdbc:postgresql://postgres-service:5432/newapirestfull
spring.datasource.username=postgres     # o el usuario que hayas definido
spring.datasource.password=academyjava  # o la contraseña que hayas asignado

# 2. Driver y dialect para Postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. JPA / Hibernate (opcional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
